config/routes.rb
Rails.application.routes.draw do

  root to: 'secure_files#index'

  resources :secure_files, only: [:index, :new, :create] do
  end
  get 'download/*full_filename', to: 'secure_files#download', as: 'download_file', format: false

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/secure_file.rb
class SecureFile < ApplicationRecord
  belongs_to :owner, class_name: 'User'

  validates :filename, presence: true, length: { in: 6..250 }
  validates :content_type, presence: true, confirmation: true

  scope :restricted, -> { where(restricted: true) }
  scope :unrestricted, -> { where(restricted: [nil,false]) }

  accepts_nested_attributes_for :owner


  ##
  # @param [ActionDispatch::Http::UploadedFile] upload_file
  def file=(upload_file)
    self.filename = "a#{SecureRandom.hex(31)}/#{upload_file.original_filename}"
    # store file
    fullpath = "#{Rails.root}/public/files/#{filename}"
    # make sure dir exists
    FileUtils.mkdir_p(File.dirname(fullpath))
    FileUtils.cp(upload_file.path,fullpath)
    self.content_type= upload_file.content_type
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :password, presence: true, length: { in: 6..250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/secure_files_controller.rb
class SecureFilesController < ApplicationController
  def index
    @files = SecureFile.unrestricted.last(100)
  end

  def new
    @file = SecureFile.new.tap{|file| file.build_owner }
  end

  def create
    @file = SecureFile.new(secure_file_params)

    if @file.save
      redirect_to secure_files_path
    else
      render action: :new
    end

  end

  def download
    send_file "#{Rails.root}/public/files/#{params[:full_filename]}", disposition: 'inline'
  end

  private

  def secure_file_params
    params.require(:secure_file).permit(
      :file, :name, :content_type_confirmation, :restricted, owner_attributes: [
        :name, :email, :password
      ]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secure_files_helper.rb
module SecureFilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecurityToy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/secure_files/index.html.erb
<h1>Your secure stored files</h1>
<h2>These are public available files</h2>
<% if @files.blank? %>
  <p>Ups, no public files available. Do you want to <%=link_to 'create one', new_secure_file_path %>?</p>
<% else %>
  <ul>
    <% @files.each do |file| %>
      <li><%=link_to file.name || File.basename(file.filename), download_file_path(full_filename: file.filename) %></li>
    <% end %>
  </ul>
  <%=link_to 'Create new file', new_secure_file_path %>

<% end %>

app/views/secure_files/new.html.erb
<h1>Create a secure file</h1>
<%= form_for @file do |f| %>
  <% if @file.errors.present? %>
    <div class="errors">
      <ul>
        <% @file.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :file, class: 'required' %>
    <%= f.file_field :file %>
  </div>

  <div>
    <%= f.label :content_type_confirmation, class: 'required' %>
    <%= f.collection_select :content_type_confirmation, [
        ['application/pdf','PDF file'],
        ['application/vnd.openxmlformats-officedocument.wordprocessingml.document','MS Word document (docx)'],
        ['application/msword','MS Word document (doc)'],
        ['image/png','PNG image'],
      ], :first, :last %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Name to show on listing' %>
  </div>

  <div>
    <%= f.label :restricted %>
    <%= f.check_box :restricted %>
  </div>

  <%= f.fields_for :owner do |u| %>
    <div class="account">

      <p>Please include access credentials to access (if restricted) or remove this file</p>

      <div>
        <%= u.label :name %>
        <%= u.text_field :name %>
      </div>


      <div>
        <%= u.label :email, class: 'required' %>
        <%= u.email_field :email %>
      </div>

      <div>
        <%= u.label :password, class: 'required' %>
        <%= u.password_field :password, autocomplete: 'new-password' %>
      </div>

    </div>
  <% end %>

  <footer>
    <%= f.submit %>
  </footer>
<% end %>